name: Run Forum Scraper

on:
  schedule:
    - cron: "0 10 * * *" # Runs every day at 10:00 UTC (adjust for UK DST if needed)
  workflow_dispatch: # Allow manual runs

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: "latest"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python scraper.py
